let selected="الكل",cart=[],PRODUCT_LIST=[];
async function boot(){try{const [pr,sr]=await Promise.all([fetch('/api/products'),fetch('/api/settings')]);if(!pr.ok)throw 0;const dbProducts=await pr.json();PRODUCT_LIST=dbProducts.length?dbProducts:PRODUCTS;if(sr.ok){const s=await sr.json();STORE_CONFIG.storeName=s.store_name||STORE_CONFIG.storeName;STORE_CONFIG.whatsapp=s.whatsapp||STORE_CONFIG.whatsapp;STORE_CONFIG.currency=s.currency||STORE_CONFIG.currency}}catch(e){PRODUCT_LIST=PRODUCTS}renderProducts();updateCart()}
document.querySelectorAll('.filters button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');selected=b.dataset.cat;renderProducts()});
function setCategory(cat){selected=cat;document.querySelectorAll('.filters button').forEach(x=>x.classList.toggle('active',x.dataset.cat===cat));renderProducts();document.getElementById('products').scrollIntoView({behavior:'smooth'});toggleSidebar(false)}
function syncSearch(v){const a=document.getElementById('search'),b=document.getElementById('sideSearch');if(a&&a.value!==v)a.value=v;if(b&&b.value!==v)b.value=v;renderProducts()}
function renderProducts(){const q=(document.getElementById('search')?.value||'').toLowerCase();const list=PRODUCT_LIST.filter(p=>(selected==='الكل'||p.category===selected)&&String(p.name||'').toLowerCase().includes(q));document.getElementById('grid').innerHTML=list.map(p=>`<article class="card"><div class="photo">${p.image&&(p.image.startsWith('http')||p.image.startsWith('/'))?`<img src="${p.image}" alt="${p.name}">`:(p.image||p.icon||'✨')}</div><div class="info"><span class="category">${p.category}</span><h3>${p.name}</h3><span class="price">${p.price} ${STORE_CONFIG.currency}</span><button class="add" onclick="add(${p.id})">🛒 أضف إلى السلة</button></div></article>`).join('')||'<p>لا توجد منتجات.</p>'}
function add(id){const p=PRODUCT_LIST.find(x=>x.id===id);if(!p)return;const i=cart.find(x=>x.id===id);i?i.qty++:cart.push({...p,qty:1});updateCart();openCart()}
function removeItem(id){cart=cart.filter(x=>x.id!==id);updateCart()}
function updateCart(){document.getElementById('cartCount').textContent=cart.reduce((s,x)=>s+x.qty,0);document.getElementById('cartItems').innerHTML=cart.length?cart.map(x=>`<div class="cartItem"><div><b>${x.name}</b><br><small>${x.qty} × ${x.price} ${STORE_CONFIG.currency}</small></div><button onclick="removeItem(${x.id})">حذف</button></div>`).join(''):'<p>السلة فارغة حالياً.</p>';document.getElementById('total').textContent=cart.reduce((s,x)=>s+x.price*x.qty,0)+' '+STORE_CONFIG.currency}
function openCart(){document.getElementById('cart').classList.add('open');document.getElementById('cartShade').classList.add('show')}
function closeCart(){document.getElementById('cart').classList.remove('open');document.getElementById('cartShade').classList.remove('show')}
function toggleSidebar(force){const side=document.querySelector('.sidebar'),over=document.getElementById('overlay');const open=typeof force==='boolean'?force:!side.classList.contains('open');side.classList.toggle('open',open);over.classList.toggle('show',open)}
function openWhatsApp(){window.open(`https://wa.me/${STORE_CONFIG.whatsapp}`,'_blank')}
function checkout(){if(!cart.length)return alert('السلة فارغة');const total=cart.reduce((s,x)=>s+x.price*x.qty,0);const lines=cart.map(x=>`• ${x.name} × ${x.qty} = ${x.price*x.qty} ${STORE_CONFIG.currency}`).join('\n');const msg=`السلام عليكم، بغيت نطلب من ${STORE_CONFIG.storeName}:\n\n${lines}\n\nالمجموع: ${total} ${STORE_CONFIG.currency}`;window.open(`https://wa.me/${STORE_CONFIG.whatsapp}?text=${encodeURIComponent(msg)}`,'_blank')}
boot();
